action:
- data:
    entity_id:
    - light.garage_walk_in_door_light_light
    - light.deck_light_light_2 
  service: light.toggle
alias: Remote Press - Toggle Backyard Lights
condition: []
description: Toggle the back porch and garage walk-in lights
id: 743d763933d74d87af8b7a1c1d37da02
trigger:
- event_data:
    command: move_to_level
    device_iee: 14:b4:57:ff:fe:82:bf:5a
  event_type: zha_event
  platform: event
