action:
- data:
    entity_id:
    - switch.xbee_xbee_io_4193fedf_210_6
  service: switch.turn_on
alias: Remote Press - Garage Toggle
condition: []
description: ''
trigger:
- event_data:
    command: 'on'
    device_ieee: 14:b4:57:ff:fe:82:bf:5a
  event_type: zha_event
  platform: event
- event_data:
    command: 'off'
    device_ieee: 14:b4:57:ff:fe:82:bf:5a
  event_type: zha_event
  platform: event
