action:
- entity_id: light.stairway_lights
  service: light.toggle
alias: Remote Press - Stair Lights Toggle
condition: []
description: 'Toggle Stair lights when remote button is pressed'
trigger:
- event_data:
    command: 'off'
    device_ieee: 14:b4:57:ff:fe:81:56:33
  event_type: zha_event
  platform: event
- event_data:
    command: 'on'
    device_ieee: 14:b4:57:ff:fe:81:56:33
  event_type: zha_event
  platform: event
