action:
- entity_id: all
  service: light.turn_off
alias: Remote Press - All Lights Off
condition: []
description: ''
trigger:
- event_data:
    command: move_to_color_temp
    device_ieee: 14:b4:57:ff:fe:81:56:33
  event_type: zha_event
  platform: event
