action:
- entity_id: light.stairway_lights_zha_group 
  service: light.toggle
alias: Remote Press - Stair Lights Toggle
condition: []
description: Toggle Stair lights when remote button is pressed
id: 18ef7e83bc8f4effbb9f802081fe2805
trigger:
- event_data:
    command: 'off'
    device_ieee: 14:b4:57:ff:fe:81:56:33
  event_type: zha_event
  platform: event
- event_data:
    command: 'on'
    device_ieee: 14:b4:57:ff:fe:81:56:33
  event_type: zha_event
  platform: event
