dist: bionic
language: python
python:
  - "3.8"
before_install:
  - sudo apt-get install -y libavformat-dev libavcodec-dev libavdevice-dev
  - sudo apt-get install -y libavutil-dev libswscale-dev libswresample-dev libavfilter-dev
  - sudo apt-get install -y libbluetooth-dev 
  - mv travis_secrets.yaml secrets.yaml
  - sudo apt-get install libgirepository1.0-dev python3-gi
  - pip3 install vext vext.gi PyGObject
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
