language: python
python:
  - "3.8"
before_install:
  - sudo apt-get install libavformat-dev libavfilter-dev libavdevice-dev ffmpeg
  - mv travis_secrets.yaml secrets.yaml
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
