language: python
python:
  - "3.8"
before_install:
  - sudo apt-get install libbluetooth-dev libavformat-dev libavfilter-dev libavdevice-dev ffmpeg
  - mv travis_secrets.yaml secrets.yaml
  - sudo apt-get install python3-gi
  - pip3 install vext vext.gi PyGObject
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
