- id: coffee_on_morn_ryan
  alias: Turn on Coffee Pot in the morning (Ryan)
  trigger:
  - at: 06:15:00
    platform: time
  condition:
  - condition: state
    entity_id: person.ryan
    state: home
  action:
  - data:
      entity_id:
      - switch.ledvance_plug_00054922_1
    service: switch.turn_on
- id: coffee_on_morn
  alias: Turn on Coffee Pot in the morning (Jeanette)
  trigger:
  - at: 07:30:00
    platform: time
  condition:
  - condition: state
    entity_id: person.jeanette
    state: home
  action:
  - data:
      entity_id:
      - switch.ledvance_plug_00054922_1
    service: switch.turn_on
- id: coffee_off_jeanette_only
  alias: Turn off the Coffee Pot off if Jeanette is home alone
  trigger:
  - at: '14:00:00'
    platform: time
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: person.ryan
      state: not_home
    - condition: state
      entity_id: person.jeanette
      state: home
  action:
  - data:
      entity_id:
      - switch.ledvance_plug_00054922_1
    service: switch.turn_off
- id: coffee_off_night
  alias: Turn off the Coffee Pot at night
  trigger:
  - at: '20:00:00'
    platform: time
  action:
  - data:
      entity_id:
      - switch.ledvance_plug_00054922_1
    service: switch.turn_off
- id: coffee_on_home_jeanette
  alias: Turn on the Coffee Pot when home (Jeanette)
  trigger:
  - entity_id: person.jeanette
    platform: state
    to: home
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: person.ryan
      state: not_home
    - condition: time
      after: 07:00:00
      before: '14:00:00'
  action:
  - data:
      entity_id:
      - switch.ledvance_plug_00054922_1
    service: switch.turn_on
- id: coffee_on_home_ryan
  alias: Turn on the Coffee Pot when home (Ryan)
  trigger:
  - entity_id: person.ryan
    platform: state
    to: home
  condition:
  - condition: time
    after: 06:15:00
    before: '20:00:00'
  action:
  - data:
      entity_id:
      - switch.ledvance_plug_00054922_1
    service: switch.turn_on
- id: coffee_off_away
  alias: Turn off the Coffee Pot when away
  trigger:
  - entity_id: group.home_owners
    platform: state
    to: not_home
  action:
  - data:
      entity_id:
      - switch.ledvance_plug_00054922_1
    service: switch.turn_off
- id: '1546826068070'
  alias: Garage Toggle On
  trigger:
  - entity_id: switch.xbee_xbee_io_4193fedf_209_6
    from: 'off'
    platform: state
    to: 'on'
  action:
    service: switch.turn_on
    data:
      entity_id:
      - switch.xbee_xbee_io_4193fedf_210_6
- id: '1546826459762'
  alias: Garage Toggle Off
  trigger:
  - entity_id: switch.xbee_xbee_io_4193fedf_209_6
    from: 'on'
    platform: state
    to: 'off'
  - entity_id: switch.xbee_xbee_io_4193fedf_210_6
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      entity_id:
      - switch.xbee_xbee_io_4193fedf_210_6
    service: switch.turn_off
- id: Garage_Ope_Alert
  alias: Garage Open Alert
  trigger:
  - platform: state
    entity_id: switch.xbee_xbee_io_4193fedf_209_6
    for: 00:05:00
    from: 'off'
    to: 'on'
  action:
    service: notify.pushbullet
    data:
      title: Garage Door Left Open Alert
      message: The garage door has been open for more than five minutes.
- id: Bed_Lght_Morn_On
  alias: Turn on bedroom lights in the morning
  trigger:
  - at: 06:15:00
    platform: time
  condition:
  - condition: state
    entity_id: person.ryan
    state: home
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - data:
      entity_id:
      - light.bedroom_lights
    service: homeassistant.turn_on
- id: Bed_Lght_Eve_Off
  alias: Turn off bedroom lights at night
  trigger:
  - at: '22:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: person.ryan
    state: home
  action:
  - data:
      entity_id:
      - light.bedroom_lights
    service: homeassistant.turn_off
- id: Lights_off_away
  alias: Turn off all lights when away
  trigger:
  - entity_id: group.home_owners
    platform: state
    to: not_home
    for:
      minutes: 5
  action:
  - data:
      entity_id:
      - group.all_lights
    service: homeassistant.turn_off
- id: greeting_come_home
  alias: Arrival Greeting
  trigger:
  - entity_id: person.ryan
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: person.jeanette
    state: not_home
  action:
  - entity_id: script.arrival
    service: homeassistant.turn_on
- id: Front_Door_Open_Alert
  alias: Front Door Opened Alert
  trigger:
  - entity_id: binary_sensor.zha_02e2146c_1_6
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: group.home_owners
    state: not_home
  action:
  - data:
      message: The front door was opened.
      title: Front Door Opened
    service: notify.pushbullet
  - entity_id: script.intruder
    service: homeassistant.turn_on
- id: Intruder_Alarm
  alias: Intruder Alarm
  trigger:
  - entity_id: binary_sensor.zha_02e2146c_1_6
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: group.home_owners
    state: not_home
  action:
  - data:
      message: Alarm activated!
      title: Alarm Activated
    service: notify.pushbullet
  - entity_id: script.intruder
    service: homeassistant.turn_on
- id: Garage_WalkIn_Open_Alert
  alias: Garage Walk In Door Opened Alert
  trigger:
  - entity_id: binary_sensor.zha_02bfe504_1_6
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: group.home_owners
    state: not_home
  action:
  - data:
      message: The garage walk in door was opened.
      title: Garage Walk-In Opened
    service: notify.pushbullet
- id: Back_Door_Open_Alert
  alias: Back Door Opened Alert
  trigger:
  - entity_id: binary_sensor.zha_02bfefd9_1_6
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: group.home_owners
    state: not_home
  action:
  - data:
      message: The back door was opened.
      title: Back Door Opened
    service: notify.pushbullet
- id: Side_Door_Open_Alert
  alias: Kitchen-Garage Door Opened Alert
  trigger:
  - entity_id: binary_sensor.zha_02ec0d9e_1_6
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: group.home_owners
    state: not_home
  action:
  - data:
      message: The kitchen to garage door was opened.
      title: Kitchen-Garage Door Opened
    service: notify.pushbullet
- id: Garage_Door_Open_Away_Alert
  alias: Garage Door Opened Alert
  trigger:
  - entity_id: switch.xbee_xbee_io_4193fedf_209_6
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: group.home_owners
    state: not_home
  action:
  - data:
      message: The garage door was opened.
      title: Garage Door Opened
    service: notify.pushbullet
- id: Skip_Door_Alert
  alias: Skip Door Alert
  trigger:
  - entity_id: binary_sensor.lumi_lumi_sensor_magnet_3b36e101_1_6
    for:
      seconds: 1
    platform: state
    to: 'off'
  condition:
  - condition: template
    value_template: '{{ (as_timestamp(now()) - as_timestamp(states.binary_sensor.zha_02ec0d9e_1_6.last_changed))
      > 5 }}

      '
  - condition: state
    entity_id: group.home_owners
    state: not_home
  action:
  - data:
      entity_id: camera.ukn_cam
      filename: /home/homeassistant/.homeassistant/www/snapshots/ukn_cam.jpg
    service: camera.snapshot
  - data:
      data:
        file: /home/homeassistant/.homeassistant/www/snapshots/ukn_cam.jpg
      message: Scipio has left or arrived!
      title: Scipio Alert
    service: notify.pushbullet
- id: dishwasher_leak_detect
  alias: Dishwasher Leak Detected
  trigger:
  - platform: state
    entity_id: binary_sensor.lumi_lumi_sensor_wleak_aq1_027b09f4_1_1280
    to: 'on'
  action:
    service: notify.pushbullet
    data:
      title: Dishwasher Leak
      message: Water leak deteted at the dishwasher!
- id: washing_machine_leak_detect
  alias: Clothes Washer Leak Detected
  trigger:
  - platform: state
    entity_id: binary_sensor.lumi_lumi_sensor_wleak_aq1_0279bc76_1_1280
    to: 'on'
  action:
    service: notify.pushbullet
    data:
      title: Washing Machine Leak
      message: Water leak deteted at the clothes washer!
- id: turn_stair_lights_on_if_door_open_night
  alias: Turn on Stair Lights if Door Opened at Night
  trigger:
  - entity_id: binary_sensor.zha_02e2146c_1_6
    platform: state
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: -4.0
  - condition: state
    entity_id: light.stairway_lights
    state: 'off'
  action:
  - data:
      brightness: 50
      entity_id: light.stairway_lights
    service: light.turn_on
- id: set_nest_away_when_away
  alias: Set Nest Away When Away
  trigger:
  - entity_id: group.home_owners
    platform: state
    to: not_home
  action:
  - data:
      away_mode: away
    service: nest.set_away_mode
- id: set_nest_home_when_home
  alias: Set Nest to Home When Home
  trigger:
  - platform: state
    entity_id: group.home_owners
    to: home
  action:
    service: nest.set_away_mode
    data:
      away_mode: home
- id: turn_circ_fan_on_when_hvac_on
  alias: Turn Circulation Fan on With HVAC
  trigger:
  - platform: state
    entity_id: sensor.downstairs_thermostat_hvac_state
    from: 'off'
  - platform: state
    entity_id: binary_sensor.downstairs_thermostat_fan
    from: 'off'
  action:
    service: light.turn_on
    data:
      entity_id: light.jasco_products_45856_00db2500_1
- id: turn_circ_fan_off_when_hvac_off
  alias: Turn Circulation Fan off With HVAC
  trigger:
  - platform: state
    entity_id: sensor.downstairs_thermostat_hvac_state
    to: 'off'
  - platform: state
    entity_id: binary_sensor.downstairs_thermostat_fan
    to: 'off'
  condition:
  - condition: state
    entity_id: sensor.downstairs_thermostat_hvac_state
    state: 'off'
  - condition: state
    entity_id: binary_sensor.downstairs_thermostat_fan
    state: 'off'
  action:
    service: light.turn_off
    data:
      entity_id: light.jasco_products_45856_00db2500_1
- id: woodpecker_alarm
  alias: Alert on Woodpecker Pecking
  trigger:
  - platform: state
    entity_id: binary_sensor.lumi_lumi_vibration_aq1_02af6e3c_1
    to: 'on'
  - platform: state
    entity_id: binary_sensor.zha_02b7eb7f_1_1280
    to: 'on'
  - platform: state
    entity_id: binary_sensor.zha_02b7eb7f_1
    to: 'on'
  action:
    service: notify.pushbullet
    data:
      title: Woodpecker Detected!
      message: Woodpecker Activity Detected!
- id: front_door_bell
  alias: Front Door Bell Rung
  trigger:
  - platform: state
    entity_id: switch.zha_40c04e54_1_6
    to: 'on'
  action:
  - service: camera.snapshot
    data:
      entity_id: camera.front_porch
      filename: /home/homeassistant/.homeassistant/www/snapshots/front_porch.jpg
  - service: notify.pushbullet
    data:
      data:
        file: /home/homeassistant/.homeassistant/www/snapshots/front_porch.jpg
      title: Front Door Alert
      message: Front Door Bell was Rung
- id: smoke_alarm_kitchen
  alias: Smoke Alarm Kitchen
  trigger:
  - platform: state
    entity_id: binary_sensor.lumi_lumi_sensor_smoke_02cb2ea9_1_1280
    to: 'on'
  action:
    service: notify.pushbullet
    data:
      title: Smoke Alarm
      message: Smoke detected in the Kitchen!
- id: xbox_set_lights
  alias: Set Lights on Netflix or Bluray
  trigger:
  - entity_id: sensor.xbox_source
    platform: state
    to: Netflix
  - entity_id: sensor.xbox_source
    platform: state
    to: Blu-ray Player
  - entity_id: sensor.xbox_source
    platform: state
    to: Plex For Xbox One
  action:
  - data:
      entity_id: switch.circadian_lighting_circadian_lighting
    service: switch.turn_off
  - data:
      entity_id: light.feibit_inc_co_fzb56_zcw27lx1_0_1c465fb1_11
      profile: movie_red
    service: light.turn_on
- id: xbox_return_lights
  alias: Return Lights to Normal Xbox
  trigger:
  - entity_id: sensor.xbox_source
    from: Netflix
    platform: state
  - entity_id: sensor.xbox_source
    from: Blu-ray Player
    platform: state
  - entity_id: sensor.xbox_source
    from: Plex For Xbox One
    platform: state
  action:
  - data:
      entity_id: switch.circadian_lighting_circadian_lighting
    service: switch.turn_on
- id: water_heater_emerg
  alias: Water Heater Emergency Heat
  trigger:
  - entity_id: sensor.zha_40c04dcb_2_1026
    below: 45
    platform: numeric_state
  action:
  - data:
      entity_id: switch.zha_40c04dcb_1_6
    service: switch.turn_on
- id: set_wh_off_when_away
  alias: Set Water Heater off When Away
  trigger:
  - entity_id: group.home_owners
    platform: state
    to: not_home
  action:
  - data:
      entity_id: switch.zha_40c04dcb_1_6
    service: switch.turn_off
- id: set_wh_on_when_home
  alias: Set Water Heater on When Home
  trigger:
  - platform: state
    entity_id: group.home_owners
    to: home
  condition:
  - condition: time
    before: '22:00:00'
    after: 05:00:00
  action:
  - data:
      entity_id: switch.zha_40c04dcb_1_6
    service: switch.turn_on
- id: set_wh_off_at_night
  alias: Set Water Heater off at night
  trigger:
  - platform: time
    at: '22:00:00'
  action:
  - data:
      entity_id: switch.zha_40c04dcb_1_6
    service: switch.turn_off
- id: set_wh_on_in_morn
  alias: Set Water Heater on in the Morning
  trigger:
  - at: 05:00:00
    platform: time
  condition:
  - condition: state
    entity_id: group.home_owners
    state: home
  action:
  - data:
      entity_id: switch.zha_40c04dcb_1_6
    service: switch.turn_on
- id: closet_on_open
  alias: Turn On Mstr Bedroom Closet Lights
  trigger:
  - platform: state
    entity_id: binary_sensor.zha_02c39915_1_6
    to: 'on'
  action:
    service: light.turn_on
    data:
      entity_id: light.master_bedroom_lights
- id: closet_on_open
  alias: Turn On Mstr Bedroom Closet Lights
  trigger:
  - platform: state
    entity_id: binary_sensor.zha_02c39915_1_6
    to: 'off'
  action:
    service: light.turn_off
    data:
      entity_id: light.master_bedroom_lights
- id: dumpster_inside
  alias: Set Dumpster Outside
  trigger:
  - at: 08:00:00
    platform: time
  - entity_id: switch.xbee_xbee_io_4193fedf_209_6
    platform: state
    to: 'on'
  condition:
  - after: 02:30:00
    before: 09:30:00
    condition: time
    weekday:
    - fri
  - condition: state
    entity_id: sensor.dumpster
    state: garage
  action:
  - data:
      message: It's trash day and the dumpster is still inside the garage.
      title: Take Dumpster Outside
    service: notify.pushbullet
- id: dumpster_outside
  alias: Bring Dumpster In
  trigger:
  - at: '11:00:00'
    platform: time
  - entity_id: switch.xbee_xbee_io_4193fedf_209_6
    platform: state
    to: 'on'
  condition:
  - after: '10:30:00'
    condition: time
    weekday:
    - fri
  - condition: state
    entity_id: sensor.dumpster
    state: not_home
  action:
  - data:
      message: The dumpster is still outside, please bring it back inside.
      title: Bring Dumpster Inside
    service: notify.pushbullet
- id: '1574467185968'
  alias: Porch Lights on at Dusk/Dawn
  description: ''
  trigger:
  - above: '-65'
    below: '-4'
    entity_id: sun.sun
    platform: numeric_state
    value_template: '{{ state.attributes.elevation }}'
  - above: '-12'
    below: '-4'
    entity_id: sun.sun
    platform: numeric_state
    value_template: '{{ state.attributes.elevation }}'
  condition:
  - condition: state
    entity_id: light.jasco_products_45856_61d32600_1
    state: 'off'
  action:
  - data:
      entity_id: light.jasco_products_45856_61d32600_1
    service: light.turn_on
- id: '1574467388406'
  alias: Porch Lights Off
  description: At 2200 or more than 1.5 deg above the horizon
  trigger:
  - at: '22:00:00'
    platform: time
  - above: '1.5'
    entity_id: sun.sun
    platform: numeric_state
    value_template: '{{ state.attributes.elevation }}'
  condition: []
  action:
  - data:
      entity_id: light.jasco_products_45856_61d32600_1
    service: light.turn_off
- id: '1574468834273'
  alias: Porch Light on if Front Door Opened
  description: ''
  trigger:
  - entity_id: binary_sensor.zha_02e2146c_1_6
    platform: state
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: -4.0
  action:
  - data:
      entity_id: light.jasco_products_45856_61d32600_1
    service: homeassistant.turn_on
