- id: coffee_on_morn
  alias: Turn on Coffee Pot in the morning
  trigger:
  - at: 06:15:00
    platform: time
  condition:
  - condition: state
    entity_id: person.ryan 
    state: not_home 
  action:
  - data:
      entity_id:
      - switch.iris_alertme_025b8357_2_238
    service: switch.turn_on
- id: coffee_off_night
  alias: Turn off the Coffee Pot at night
  trigger:
  - at: '20:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: person.ryan 
    state: not_home
  action:
  - data:
      entity_id:
      - switch.iris_alertme_025b8357_2_238
    service: switch.turn_off
- id: coffee_on_home
  alias: Turn on the Coffee Pot when home
  trigger:
  - entity_id: person.ryan 
    platform: state
    to: not_home
  action:
  - data:
      entity_id:
      - switch.iris_alertme_025b8357_2_238
    service: switch.turn_on
- id: coffee_off_away
  alias: Turn off the Coffee Pot when away
  trigger:
  - entity_id: person.ryan 
    platform: state
    to: home
  action:
  - data:
      entity_id:
      - switch.iris_alertme_025b8357_2_238
    service: switch.turn_off
- id: '1546826068070'
  alias: Garage Toggle On
  trigger:
  - entity_id: switch.xbee_xbee_io_4193fedf_209_6
    from: 'off'
    platform: state
    to: 'on'
  action:
    service: switch.turn_on
    data:
      entity_id:
      - switch.xbee_xbee_io_4193fedf_210_6
- id: '1546826459762'
  alias: Garage Toggle Off
  trigger:
  - platform: state
    entity_id: switch.xbee_xbee_io_4193fedf_209_6
    for: 00:00:01
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: switch.xbee_xbee_io_4193fedf_210_6
    for: 00:00:01
    from: 'off'
    to: 'on'
  action:
    service: switch.turn_off
    data:
      entity_id:
      - switch.xbee_xbee_io_4193fedf_210_6
- id: Garage_Ope_Alert
  alias: Garage Open Alert
  trigger:
  - platform: state
    entity_id: switch.xbee_xbee_io_4193fedf_209_6
    for: 00:05:00
    from: 'off'
    to: 'on'
  action:
    service: notify.pushbullet
    data:
      title: Garage Door Left Open Alert
      message: The garage door has been open for more than five minutes.
- id: Bed_Lght_Morn_On
  alias: Turn on bedroom lights in the morning
  trigger:
  - at: 05:30:00
    platform: time
  condition:
  - condition: state
    entity_id: person.ryan 
    state: home
  - condition: state
    entity_id: binary_sensor.workday
    state: 'on'
  action:
  - data:
      entity_id:
      - light.bedroom_lights 
    service: homeassistant.turn_on
- id: Bed_Lght_Eve_Off
  alias: Turn off bedroom lights at night
  trigger:
  - at: '22:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: person.ryan 
    state: home
  action:
  - data:
      entity_id:
      - light.bedroom_lights
    service: homeassistant.turn_off
- id: Lights_off_away
  alias: Turn off all lights when away
  trigger:
  - entity_id: person.ryan 
    platform: state
    to: not_home
  action:
  - data:
      entity_id:
      - group.all_lights
    service: homeassistant.turn_off
- id: greeting_come_home
  alias: Arrival Greeting
  trigger:
  - entity_id: person.ryan 
    platform: state
    to: home
  action:
  - entity_id: script.arrival
    service: homeassistant.turn_on
- id: Front_Door_Open_Alert
  alias: Front Door Opened Alert
  trigger:
  - entity_id: binary_sensor.zha_02e2146c_1_6
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: person.ryan 
    state: not_home
  action:
  - data:
      message: The front door was opened.
      title: Front Door Opened
    service: notify.pushbullet
  - entity_id: script.intruder
    service: homeassistant.turn_on
- id: Garage_WalkIn_Open_Alert
  alias: Garage Walk In Door Opened Alert
  trigger:
  - entity_id: binary_sensor.zha_02bfe504_1_6
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: person.ryan 
    state: not_home
  action:
  - data:
      message: The garage walk in door was opened.
      title: Garage Walk-In Opened
    service: notify.pushbullet
- id: Back_Door_Open_Alert
  alias: Back Door Opened Alert
  trigger:
  - entity_id: binary_sensor.zha_02bfefd9_1_6
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: person.ryan 
    state: not_home
  action:
  - data:
      message: The back door was opened.
      title: Back Door Opened
    service: notify.pushbullet
- id: Side_Door_Open_Alert
  alias: Kitchen-Garage Door Opened Alert
  trigger:
  - entity_id: binary_sensor.zha_02ec0d9e_1_6
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: person.ryan 
    state: not_home
  action:
  - data:
      message: The kitchen to garage door was opened.
      title: Kitchen-Garage Door Opened
    service: notify.pushbullet
- id: Garage_Door_Open_Away_Alert
  alias: Garage Door Opened Alert
  trigger:
  - entity_id: switch.xbee_xbee_io_4193fedf_209_6
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: person.ryan 
    state: not_home
  action:
  - data:
      message: The garage door was opened.
      title: Garage Door Opened
    service: notify.pushbullet
- id: Skip_Door_Alert
  alias: Skip Door Alert
  trigger:
  - platform: state
    entity_id: binary_sensor.lumi_lumi_sensor_magnet_01e1363b_1
    to: 'off'
    for:
      seconds: 1
  condition:
  - condition: template
    value_template: '{{ (as_timestamp(now()) - as_timestamp(states.binary_sensor.zha_02ec0d9e_1_6.last_changed))
      > 5 }}

      '
  action:
    service: notify.pushbullet
    data:
      title: Scipio Alert
      message: Scipio has left or arrived!
- id: dishwasher_leak_detect
  alias: Dishwasher Leak Detected
  trigger:
  - platform: state
    entity_id: binary_sensor.lumi_lumi_sensor_wleak_aq1_027b09f4_1_1280
    to: 'on'
  action:
    service: notify.pushbullet
    data:
      title: Dishwasher Leak
      message: Water leak deteted at the dishwasher!
- id: washing_machine_leak_detect
  alias: Clothes Washer Leak Detected
  trigger:
  - platform: state
    entity_id: binary_sensor.lumi_lumi_sensor_wleak_aq1_0279bc76_1_1280
    to: 'on'
  action:
    service: notify.pushbullet
    data:
      title: Washing Machine Leak
      message: Water leak deteted at the clothes washer!
- id: turn_stair_lights_on_if_door_open_night
  alias: Turn on Stair Lights if Door Opened at Night
  trigger:
  - platform: state
    entity_id: binary_sensor.zha_02e2146c_1_6
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
    service: light.turn_on
    data:
      entity_id: light.stairway_lights
      brightness: 50
- id: set_nest_away_when_away
  alias: Set Nest Away When Away
  trigger:
  - entity_id: person.ryan 
    platform: state
    to: not_home
  action:
  - data:
      away_mode: away
    service: nest.set_away_mode
- id: set_nest_home_when_home
  alias: Set Nest to Home When Home
  trigger:
  - platform: state
    entity_id: person.ryan 
    to: home
  action:
    service: nest.set_away_mode
    data:
      away_mode: home
- id: turn_circ_fan_on_when_hvac_on
  alias: Turn Circulation Fan on With HVAC
  trigger:
  - platform: state
    entity_id: sensor.downstairs_thermostat_hvac_state
    from: 'off'
  - platform: state
    entity_id: binary_sensor.downstairs_thermostat_fan
    from: 'off'
  action:
    service: light.turn_on
    data:
      entity_id: light.sz_lamp_01_1baff16c_11
- id: turn_circ_fan_off_when_hvac_off
  alias: Turn Circulation Fan off With HVAC
  trigger:
  - platform: state
    entity_id: sensor.downstairs_thermostat_hvac_state
    to: 'off'
  - platform: state
    entity_id: binary_sensor.downstairs_thermostat_fan
    to: 'off'
  condition:
  - condition: state
    entity_id: sensor.downstairs_thermostat_hvac_state
    state: 'off'
  - condition: state
    entity_id: binary_sensor.downstairs_thermostat_fan
    state: 'off'
  action:
    service: light.turn_off
    data:
      entity_id: light.sz_lamp_01_1baff16c_11
- id: woodpecker_alarm
  alias: Alert on Woodpecker Pecking
  trigger:
  - platform: state
    entity_id: binary_sensor.lumi_lumi_vibration_aq1_02af6e3c_1
    to: 'on'
  - platform: state
    entity_id: binary_sensor.zha_02b7eb7f_1_1280
    to: 'on'
  - platform: state
    entity_id: binary_sensor.zha_02b7eb7f_1
    to: 'on'
  action:
    service: notify.pushbullet
    data:
      title: Woodpecker Detected!
      message: Woodpecker Activity Detected!
- id: front_door_bell
  alias: Front Door Bell Rung
  trigger:
  - platform: state
    entity_id: switch.zha_40c04e54_1_6
    to: 'on'
  action:
    - service: camera.snapshot
      data:
          entity_id: camera.front_porch
          filename: '/home/homeassistant/.homeassistant/www/snapshots/front_porch.jpg'
    - service: notify.pushbullet 
      data:
        data:
          file: '/home/homeassistant/.homeassistant/www/snapshots/front_porch.jpg'
        title: Front Door Alert
        message: Front Door Bell was Rung
- id: smoke_alarm_kitchen
  alias: Smoke Alarm Kitchen
  trigger:
  - platform: state
    entity_id: binary_sensor.lumi_lumi_sensor_smoke_02cb2ea9_1_1280 
    to: 'on'
  action:
    service: notify.pushbullet
    data:
      title: Smoke Alarm
      message: Smoke detected in the Kitchen!

