- platform: workday
  country: US 
  province: TN
  workdays: [mon, tue, wed, thu, fri]
- platform: template
  sensors:
    door:
    device_class: garage_door
    value_template: "{{ is_state('switch.xbee_xbee_io_4193fedf_211_6', 'on') }}"