frontend:
  extra_html_url:
    - /local/hass-bha-icons.html

http:
  base_url: !secret ha_url
  use_x_forwarded_for: true
  trusted_proxies: !secret ha_ip

weather:
  - platform: darksky
    api_key: !secret darksky_api_key

logger:
  default: warning
  logs: !include zigbee_logging.yaml

device_tracker:
  - platform: bluetooth_tracker

pi_hole:
  api_key: !secret pi_hole_api_key

zoneminder:
 - host: !secret zm_host 
   username: !secret zm_uid
   password: !secret zm_pwd 

upnp:
  sensors: true
  local_ip: !secret local_ip 

stream:
circadian_lighting:
system_health:
person:
cloud:
lovelace:
config:
mobile_app:
updater:
discovery:
conversation:
logbook:
map:
sun:

!include_dir_named config_files/


# binary_sensor: !include binary_sensor.yaml
# camera: !include camera.yaml
# fan: !include fan.yaml
# group: !include groups.yaml
# history: !include history.yaml
# homeassistant: !include homeassistant.yaml
# input_number: !include input_number.yaml
# light: !include light.yaml
# media_player: !include media_player.yaml  
# mqtt: !include mqtt.yaml
# nest: !include nest.yaml
# notify: !include notify.yaml
# recorder: !include recorder.yaml
# script: !include script.yaml
# sensor: !include sensor.yaml
# switch: !include switch.yaml
# tts: !include tts.yaml
# zha: !include zha.yaml
# zone: !include zones.yaml









automation: !include automations.yaml
