frontend:

http:
  base_url: !secret ha_url
  use_x_forwarded_for: true
  trusted_proxies: !secret ha_ip

weather:
  - platform: darksky
    api_key: !secret darksky_api_key

logger:
  default: warning
#  logs: !include zigbee_logging.yaml

device_tracker:
  - platform: bluetooth_tracker

pi_hole:
  api_key: !secret pi_hole_api_key
  host: !secret pi_hole_ip

zoneminder:
 - host: !secret zm_host 
   username: !secret zm_uid
   password: !secret zm_pwd 

upnp:
  local_ip: !secret local_ip 

tdameritrade:
  consumer_key: ROTH_TRADER2@AMER.OAUTHAP 

stream:
circadian_lighting:
system_health:
person:
cloud:
lovelace:
config:
mobile_app:
updater:
discovery:
conversation:
logbook:
map:
sun:

binary_sensor: !include config_files/binary_sensor.yaml
camera: !include config_files/camera.yaml
fan: !include config_files/fan.yaml
group: !include config_files/groups.yaml
history: !include config_files/history.yaml
homeassistant: !include config_files/homeassistant.yaml
input_number: !include config_files/input_number.yaml
light: !include config_files/light_groups.yaml
media_player: !include config_files/media_player.yaml  
mqtt: !include config_files/mqtt.yaml
nest: !include config_files/nest.yaml
notify: !include config_files/notify.yaml
recorder: !include config_files/recorder.yaml
sensor: !include config_files/sensor.yaml
switch: !include config_files/switch.yaml
tts: !include config_files/tts.yaml
zha: !include config_files/zha.yaml
zone: !include config_files/zones.yaml

script: !include_dir_named scripts/
automation: !include automations.yaml
automation old: !include_dir_list automations/
