homeassistant:
  name: !secret ha_name 
  latitude: !secret home_lat 
  longitude: !secret home_long 
  elevation: 727
  unit_system: imperial 
  time_zone: America/New_York
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  api_password: !secret http_api_pwd 

updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Sensors
sensor:
  - platform: plex
    host: !secret plex_ip
    name: Son of Joel (Plex)
    token: !secret plex_token 
    port: 32400
    #  - platform: fedex
    #username: !secret fedex_uid
    #password: !secret fedex_pwd
  - platform: ups
    username: !secret ups_uid
    password: !secret ups_pwd

binary_sensor:
  - platform: workday
    country: US 
    province: TN
    workdays: [mon, tue, wed, thu, fri]

    #usps:
    #username: !secret usps_uid
    #password: !secret usps_pwd
    #driver: phantomjs
   
tts:
  - platform: microsoft
    api_key: !secret msft_tts_key 
    language: en-gb
    gender: Female
    type: Susan, Apollo
media_player:
  - platform: onkyo
    host: !secret avr_ip 
    sources:
      hdmi-6: 'ha'
      hdmi-5: 'hdmi-5'
      strm-box: 'Strm-Box'
      bd: 'XBOX'
      bluetooth: 'Bluetooth'
      # usb_usb: 'USB'
      # network_net: 'Network'
      fm: 'Radio'
      am: 'AM'
      video4: 'Video 4'
      video3: 'Game'
      video2: 'Cable/Sat'
      #'cd_tv/cd': 'CD'
      tv: 'TV'
      phono: 'Phono'
      aux: 'AUX'
    name: receiver
  - platform: gstreamer
  - platform: plex
  - platform: xboxone
    device: FD00472764D4AE81
    name: Xbox One
  - platform: samsungtv
    host: !secret livingroomtv_ip
    #  - platform: vlc
    # name: vlc


nest:
  client_id: !secret nest_client_id 
  client_secret: !secret nest_client_secret 
  sensors:
    monitored_conditions:
      - temperature
      - target
      - humidity
      - operation_mode
      - hvac_state

weather:
  - platform: darksky
    api_key: !secret darksky_api_key

cloud:

lovelace:
  mode: yaml

zha:
  radio_type: xbee
  usb_path: /dev/ttyUSB0
  database_path: /home/homeassistant/.homeassistant/zigbee.db 
  baudrate: 115200 

mqtt:
  broker: !secret mqtt_path 
  discovery: true
  discovery_prefix: !secret mqtt_prefix 
  birth_message:
    topic: !secret mqtt_status
    payload: 'online'
  will_message:
    topic: !secret mqtt_status
    payload: 'offline'

logger:
  default: error 
  logs: !include zigbee_logging.yaml
  #media_player.onkyo: debug

system_health:

group: !include groups.yaml

light: !include light_groups.yaml

person:

automation: !include automations.yaml
script: !include scripts.yaml


device_tracker:
  - platform: bluetooth_tracker
  - platform: unifi
    host: !secret unifi_host
    username: !secret unifi_uid
    password: !secret unifi_pwd
    verify_ssl: false
    ssid_filter:
      - 'PrairieSnpr'

recorder:
  purge_keep_days: 5
  db_url: !secret recorder_url 

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key 

circadian_lighting:

switch:
  - platform: circadian_lighting
    lights_xy:
     - light.bedroom_lights
    lights_brightness:
      - light.stairway_lights
fan:
  - platform: template
    fans:
      upstairs_hvac_fan:
        friendly_name: "Upstairs HVAC Blower"
        value_template: "{{ states('light.sz_lamp_01_1baff16c_11') }}"
        turn_on:
          service: homeassistant.turn_on
          entity_id: light.sz_lamp_01_1baff16c_11 
        turn_off:
          service: homeassistant.turn_off
          entity_id: light.sz_lamp_01_1baff16c_11 
