frontend:
  themes: !include_dir_merge_named themes

http:
  use_x_forwarded_for: true
  trusted_proxies: !secret ha_ip

weather:
  - platform: darksky
    api_key: !secret darksky_api_key

logger:
  default: warning

device_tracker:
  - platform: bluetooth_tracker

rest_command:
  xbox_server_auth:
    url: !secret xbox_load_auth

nest:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret 
  project_id: !secret google_proj_id 

husqvarna_automower:
  client_id: !secret husqvarna_apikey
  client_secret: !secret husqvarna_client_secret

stream:
system_health:
person:
cloud:
lovelace:
config:
mobile_app:
discovery:
conversation:
logbook:
map:
sun:
media_source:
wake_on_lan:
backup:
counter:
dhcp:
energy:
image:
input_boolean:
input_button:
input_select:
input_text:
scene:
ssdp:
stream:
system_health:
tag:
timer:
usb:
webhook:
zeroconf:



adaptive_lighting: !include config_files/adaptive_lighting.yaml
binary_sensor: !include config_files/binary_sensor.yaml
camera: !include config_files/camera.yaml
fan: !include config_files/fan.yaml
group: !include config_files/groups.yaml
history: !include config_files/history.yaml
homeassistant: !include config_files/homeassistant.yaml
input_number: !include config_files/input_number.yaml
light: !include config_files/light_groups.yaml
media_player: !include config_files/media_player.yaml
mqtt: !include config_files/mqtt.yaml
notify: !include config_files/notify.yaml
recorder: !include config_files/recorder.yaml
sensor: !include config_files/sensor.yaml
switch: !include config_files/switch.yaml
tts: !include config_files/tts.yaml
zha: !include config_files/zha.yaml
zone: !include config_files/zones.yaml
input_datetime: !include config_files/input_datetime.yaml

script: !include_dir_named scripts/
automation: !include automations.yaml
automation old: !include_dir_list automations/
