action:
  data_template:
    variables:
      account: '{{ states.sensor.available_funds_6227.attributes.accountId }}'
      av_funds: '{{ states.sensor.available_funds_6227.state }}'
      ticker: VOO
  entity_id: script.buy_stock_ira
  service: homeassistant.turn_on
alias: Place order for VOO in Jeanette's Roth
condition:
- condition: state
  entity_id: binary_sensor.market
  state: 'on'
description: Buy VOO with all available funds in Jeanette's Roth account
id: 2e13cbc9cb044f809c737ca40753b8f6
trigger:
- at: 09:46:00
  platform: time
