alias: Place roth order
description: Buy selected stock with all available funds in Roth account
trigger:
- at: 00:09:30
  platform: time
condition:
- condition: state
  entity_id: binary_sensor.market
  state: 'on'
action:
- service: script.buy_spmd_in_roth
