alias: Place order for VOO in Ryan's Roth 
description: Buy VOO with all available funds in Ryan's Roth account
trigger:
- at: 09:45:00
  platform: time
condition:
- condition: state
  entity_id: binary_sensor.market
  state: 'on'
action:
  service: homeassistant.turn_on 
  entity_id: script.buy_stock_ira
  data_template:
    variables:
      ticker: VOO 
      account: "{{ states.sensor.available_funds_0218.attributes.accountId }}"  
      av_funds: "{{ states.sensor.available_funds_0218.state }}"
