action:
- data:
    data:
      priority: high
      ttl: 0
    message: Alarm activated!
    title: Alarm Activated
  service: notify.all_android_devices
- data:
    data:
      push:
        sound:
          critical: 1
          name: default
          volume: 1.0
    message: Alarm activated!
    title: Alarm Activated
  service: notify.all_ios_devices
- entity_id: script.intruder_alarm
  service: homeassistant.turn_on
alias: Intruder Alarm
condition:
- condition: state
  entity_id: group.home_owners
  state: not_home
id: 54e6fbb64e5c445caafffd919d231805
trigger:
- entity_id: binary_sensor.zha_02e2146c_1_6
  platform: state
  to: 'on'
