action:
- data:
    message: Alarm activated!
    title: Alarm Activated
    data:
      ttl: 0
      priority: high
  service: notify.all_android_devices
- data:
    message: Alarm activated!
    title: Alarm Activated
    data:
      push:
        sound:
          name: default
          critical: 1
          volume: 1.0
  service: notify.all_ios_devices
- entity_id: script.intruder_alarm
  service: homeassistant.turn_on
alias: Intruder Alarm
condition:
- condition: state
  entity_id: group.home_owners
  state: not_home
trigger:
- entity_id: binary_sensor.zha_02e2146c_1_6
  platform: state
  to: 'on'
