action:
- data:
    data:
      push:
        sound:
          critical: 1
          name: default
          volume: 1.0
    message: 'ZFS Pool: The Metropolitan Library is {{ trigger.to_state.state
      }}'
    title: ZFS Pool {{ trigger.to_state.state }}
  service: notify.all_ios_devices
- data:
    data:
      priority: high
      ttl: 0
    message: 'ZFS Pool: The Metropolitan Library is {{ trigger.to_state.state
      }}'
    title: ZFS Pool {{ trigger.to_state.state }}
  service: notify.all_android_devices
alias: ZFS Pool Metropolitan Library Unhealthy
id: 0a257e6f8b5c45258c34f2be38068a65
trigger:
- entity_id: sensor.zfs_metropolitan_pool_state
  from: ONLINE 
  platform: state
  for: "00:10:00"
