action:
- data:
    data:
      push:
        sound:
          critical: 1
          name: default
          volume: 1.0
    message: Smoke detected in the Kitchen!
    title: Smoke Alarm
  service: notify.all_ios_devices
- data:
    data:
      priority: high
      ttl: 0
    message: Smoke detected in the Kitchen!
    title: Smoke Alarm
  service: notify.all_android_devices
alias: Smoke Alarm Kitchen
id: d7cdad646254479194e59ddfbbe68d02
trigger:
- entity_id: binary_sensor.lumi_lumi_sensor_smoke_iaszone 
  platform: state
  to: 'on'
