action:
- data:
    data:
      push:
        sound:
          critical: 1
          name: default
          volume: 1.0
    message: Server Power Resotred!
    title: Server Power Restored
  service: notify.all_ios_devices
- data:
    data:
      priority: high
      ttl: 0
    message: Server Power Restored!
    title: Server Power Resotred
  service: notify.all_android_devices
alias: Server Power Resotred
id: 6f61d4807b8943539bed0205fe379bd7
trigger:
- entity_id: sensor.serverroom_status
  from: On Battery Battery Discharging
  platform: state
  to: Online
- entity_id: sensor.serverroom_status
  platform: state
  to: Online Battery Charging
