action:
- data:
    message: Server Power Loss!
    title: Server Power Loss 
    data:
      push:
        sound:
          name: default
          critical: 1
          volume: 1.0
  service: notify.all_ios_devices
- data:
    message: Server Power Loss!
    title: Server Power Loss
    data:
      ttl: 0
      priority: high
  service: notify.all_android_devices
alias: Server Power Loss 
trigger:
- entity_id: sensor.serverroom_status 
  platform: state
  to: 'On Battery Battery Discharging'
