action:
  data:
    message: Woodpecker Activity Detected!
    title: Woodpecker Detected!
  service: notify.all_android_devices
alias: Alert on Woodpecker Pecking
id: 3108b1820e244706b185009d3f7f609d
trigger:
- entity_id: binary_sensor.lumi_lumi_vibration_aq1_iaszone 
  platform: state
  to: 'on'
