alias: Notify of events
trigger:
  platform: mqtt
  topic: frigate/events
condition:
  condition: and
  conditions:
    - condition: template
      value_template: "{{ trigger.payload_json['type'] == 'new' }}"
    - condition: or
      conditions:
        - condition: template
          value_template: "{{ trigger.payload_json['after']['camera'] == 'front_porch' }}"
        - condition: template
          value_template: "{{ trigger.payload_json['after']['camera'] == 'back_yard' }}" 
    - condition: or
      conditions:
        - condition: template
          value_template: "{{ trigger.payload_json['after']['label'] == 'person' }}"
        - condition: template
          value_template: "{{ trigger.payload_json['after']['label'] == 'dog' }}"
action:
  - variables:
      ha_url_var: !secret ha_url
  - service: notify.all_ios_devices 
    data_template:
      message: 'A {{trigger.payload_json["after"]["label"]}} was detected in the ({{trigger.payload_json["after"]["entered_zones"] | join(", ")}}).'
      data:
        attachment:
          url: '{{ha_url_var}}/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg' 
          content-type: jpg
          hide-thumbnail: false
  - service: notify.pushbullet
    data_template:
      title: 'A {{trigger.payload_json["after"]["label"]}} was detected.'
      message: 'A {{trigger.payload_json["after"]["label"]}} was detected in the ({{trigger.payload_json["after"]["entered_zones"] | join(", ")}}).'
      data:
        file_url: '{{ha_url_var}}/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg'
