action:
- data:
    entity_id:
    - switch.ledvance_plug_00054922_1
  service: switch.turn_on
alias: Turn on Coffee Pot in the morning
condition:
- condition: state
  entity_id: group.home_owners 
  state: home
trigger:
- at: sensor.coffee_start_time 
  platform: time
