action:
- data:
    entity_id:
    - switch.bunn_coffee_pot_switch 
  service: switch.turn_off
alias: Turn off the Coffee Pot when away
id: 3cd110d4bd3d4c80af7822de40ec6caa
trigger:
- entity_id: group.home_owners
  platform: state
  to: not_home
