action:
- data:
    data:
      priority: high
      ttl: 0
    message: The back door was opened.
    title: Back Door Opened
  service: notify.all_android_devices
- data:
    data:
      push:
        sound:
          critical: 1
          name: default
          volume: 1.0
    message: The back door was opened.
    title: Back Door Opened
  service: notify.all_ios_devices
alias: Back Door Opened Alert
condition:
- condition: state
  entity_id: group.home_owners
  state: not_home
id: b9bee00d0cb64d5ba90a962843e72844
trigger:
- entity_id: binary_sensor.zha_02bfefd9_1_6
  platform: state
  to: 'on'
