action:
- data:
    message: The garage door has been open for more than five minutes.
    title: Garage Door Left Open Alert
  service: notify.all_ios_devices
- data:
    message: The garage door has been open for more than five minutes.
    title: Garage Door Left Open Alert
  service: notify.all_android_devices
alias: Garage Open Alert
id: 140b31250909400d8ed945b80e9805fb
trigger:
- entity_id: switch.garage_door_switch_4 
  for: 00:05:00
  from: 'off'
  platform: state
  to: 'on'
