action:
  - data:
      message: The garage door has been open for more than five minutes.
      title: Garage Door Left Open Alert
    service: notify.all_ios_devices
  - data:
      message: The garage door has been open for more than five minutes.
      title: Garage Door Left Open Alert
    service: notify.all_android_devices
alias: Garage Open Alert
trigger:
  - entity_id: binary_sensor.door
    for: "00:05:00"
    from: "off"
    platform: state
    to: "on"
