action:
- data:
    data:
      priority: high
      ttl: 0
    message: The kitchen to garage door was opened.
    title: Kitchen-Garage Door Opened
  service: notify.all_android_devices
- data:
    data:
      push:
        sound:
          critical: 1
          name: default
          volume: 1.0
    message: The kitchen to garage door was opened.
    title: Kitchen-Garage Door Opened
  service: notify.all_ios_devices
alias: Kitchen-Garage Door Opened Alert
condition:
- condition: state
  entity_id: group.home_owners
  state: not_home
id: 116f9c0ab37b4a9baffa07f5a2d79b6f
trigger:
- entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_opening_4 
  from: 'off'
  platform: state
  to: 'on'
