action:
- data:
    entity_id: camera.ukn_cam
    filename: /home/homeassistant/.homeassistant/www/snapshots/ukn_cam.jpg
  service: camera.snapshot
- data:
    data:
      file: /home/homeassistant/.homeassistant/www/snapshots/ukn_cam.jpg
    message: Scipio has left or arrived!
    title: Scipio Alert
  service: notify.pushbullet
alias: Skip Door Alert
condition:
- condition: template
  value_template: '{{ (as_timestamp(now()) - as_timestamp(states.binary_sensor.zha_02ec0d9e_1_6.last_changed))
    > 5 }}'
- condition: state
  entity_id: group.home_owners
  state: not_home
trigger:
- entity_id: binary_sensor.lumi_lumi_sensor_magnet_3b36e101_1_6
  for:
    seconds: 1
  platform: state
  to: 'off'
