action:
- data:
    entity_id: light.feibit_inc_co_fzb56_zcw27lx1_0_b15f461c_level_light_color_on_off
    profile: skyrim_blue
  service: light.turn_on
alias: Set Lights on Skyrim
trigger:
- entity_id: sensor.xbox_source
  platform: state
  to: 'The Elder Scrolls V: Skyrim Special Edition'
