action:
- data:
    entity_id: light.feibit_inc_co_fzb56_zcw27lx1_0_b15f461c_level_light_color_on_off
    profile: movie_red
  service: light.turn_on
alias: Set Lights on Netflix or Bluray
condition:
  condition: or
  conditions:
  - condition: template
    value_template: '{{ ''Netflix'' in trigger.to_state.state }}'
  - condition: template
    value_template: '{{ ''Blu-ray'' in trigger.to_state.state }}'
  - condition: template
    value_template: '{{ ''Plex'' in trigger.to_state.state }}'
  - condition: template
    value_template: '{{ ''Amazon'' in trigger.to_state.state }}'
  - condition: template
    value_template: '{{ ''Disney'' in trigger.to_state.state }}'
id: 7bf524de9f104eadac9d8c8f774659ea
trigger:
  entity_id: sensor.xbox_source
  platform: state
