action:
- data:
    entity_id: light.feibit_inc_co_fzb56_zcw27lx1_0_b15f461c_level_light_color_on_off
    profile: xbox_green
  service: light.turn_on
alias: Set Lights on Home Screen
id: 7194f465b5f9423f890324b3c6005935
trigger:
- entity_id: sensor.xbox_source
  platform: state
  to: Home
