action:
- data:
    entity_id: light.feibit_inc_co_fzb56_zcw27lx1_0_b15f461c_level_light_color_on_off
    profile: warm_white
  service: light.turn_on
alias: Return Lights to Normal Xbox
trigger:
- entity_id: sensor.xbox_source
  platform: state
  to: ""
