alias: Notify on mower stopped
id: 5aeeff0f-0d82-472b-bd65-4f980aecdb6d
trigger:
  - platform: state
    entity_id: sensor.aeinarr_problem_sensor 
    to: 'STOPPED' 
action:
  - variables:
      ha_url_var: !secret ha_url
  - service: notify.all_ios_devices 
    data_template:
      message: '{{ state_attr("vacuum.aeinarr", "friendly_name") }} has been stopped by an otherworldly force.' 
      data:
        attachment:
          url: '{{ha_url_var}}{{ state_attr("camera.aeinarr", "entity_picture") }}'
          content-type: jpg
          hide-thumbnail: false
  - service: notify.all_android_devices
    data_template:
      title: '{{ state_attr("vacuum.aeinarr", "friendly_name") }} Quest Update!'
      message: '{{ state_attr("vacuum.aeinarr", "friendly_name") }} has been stopped by an otherworldly force.'
      data:
        image: '{{ha_url_var}}{{ state_attr("camera.aeinarr", "entity_picture") }}' 
