action:
- data:
    message: Water leak deteted at the clothes washer!
    title: Washing Machine Leak
    data:
      push:
        sound:
          name: default
          critical: 1
          volume: 1.0
  service: notify.all_ios_devices
- data:
    message: Water leak deteted at the clothes washer!
    title: Washing Machine Leak
    data:
      ttl: 0
      priority: high
  service: notify.all_android_devices
alias: Clothes Washer Leak Detected
trigger:
- entity_id: binary_sensor.lumi_lumi_sensor_wleak_aq1_0279bc76_1_1280
  platform: state
  to: 'on'
