action:
- data:
    entity_id:
    - fan.master_bath_fan
  service: fan.turn_off
alias: Master Bathroom Fan Off Time
condition:
- condition: state
  entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_occupancy_3 
  state: 'off'
- condition: template
  value_template: '{{ sensor.lumi_lumi_weather_humidity.state < states.input_number.bath_fan_off.state
    }}'
description: Turn off bathroom fan when humidity is below setpoint, unocuppied and
  on for more than ten min.
id: c3e05421233847b8881f8f31ea7d6aad
trigger:
  entity_id: fan.master_bath_fan
  for:
    minutes: 10
  platform: state
  to: 'on'
