action:
- data:
    entity_id:
    - fan.master_bath_fan
  service: fan.turn_off
alias: Master Bathroom Fan Off humidity
condition:
  condition: state
  entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_4cd42104_occupancy
  state: 'off' 
description: Turn off bathroom fan when humidity is below setpoint
trigger:
  for:
    hours: 0
    minutes: 2
    seconds: 0
  platform: template
  value_template: '{{ states.sensor.lumi_lumi_weather_02c9fa4a_1_1029.state < states.input_number.bath_fan_off.state
    }}'
