action:
- data:
    entity_id:
    - fan.master_bath_fan
  service: fan.turn_off
alias: Master Bathroom Fan Off humidity
condition:
  condition: state
  entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_iaszone_3
  state: 'off'
description: Turn off bathroom fan when humidity is below setpoint
id: 0cd07f0891be47d7a475e7d2ead84214
trigger:
  for:
    hours: 0
    minutes: 2
    seconds: 0
  platform: template
  value_template: '{{ states.sensor.lumi_lumi_weather_humidity.state < states.input_number.bath_fan_off.state
    }}'
