- platform: workday
  country: US 
  province: TN
  workdays: [mon, tue, wed, thu, fri]
- platform: template
  sensors:
    door:
      device_class: garage_door
      value_template: "{{ is_state('switch.xbee_xbee_io_4193fedf_211_6', 'on') }}"
    ballam_in_light:
      value_template: "{{ states('sensor.ballam_light_sensor')|float > 1 }}"
- platform: bayesian
  name: "in_bed"
  prior: 0.33 # In bed 8hrs of the day so 8/24
  probability_threshold: 0.80
  observations:
    - platform: state
      entity_id: sensor.ballam_charger_type
      prob_given_true: 0.33 # Wireless charging 8hrs of the day
      prob_given_false: 0.042 # Wireless charging 1hrs of the day when working
      to_state: 'wireless'
    - platform: state
      entity_id: light.bedroom_bed_lights_zha_group_0x0004
      prob_given_true: 0.042 # lights on while in bed, 1 hr of the day
      prob_given_false: 0.17 # lights on while not in bed, 4 hrs of the day
      to_state: 'on'
    - platform: state
      entity_id: media_player.receiver
      prob_given_true: 0.021 # 30 min on while in bed
      prob_given_false: 0.33 # 8hrs off while in bed
      to_state: 'on'
    - platform: state
      entity_id: binary_sensor.ballam_in_light 
      prob_given_true: 0.33 # 8hrs a day in bedroom
      prob_given_false: 0.17 # 4hrs a day tv    
      to_state: 'off'
    - platform: state
      entity_id: light.osram_lightify_a19_rgbw_00a434be_3
      prob_given_true: 0.33 # Lights off 8 hrs while sleeping
      prob_given_false: 0.15 # lights off 4 hrs while not sleeping, (weekends though)
      to_state: 'off'
  
