- platform: template
  fans:
    upstairs_hvac_fan:
      friendly_name: "Upstairs HVAC Blower"
      value_template: "{{ states('light.hvac_booster_fan_light_2') }}"
      turn_on:
        service: homeassistant.turn_on
        entity_id: light.hvac_booster_fan_light_2 
      turn_off:
        service: homeassistant.turn_off
        entity_id: light.hvac_booster_fan_light_2 
    downstairs_bath_fan:
      friendly_name: "Downstairs Bathroom Fan"
      value_template: "{{ states('light.lumi_lumi_relay_c2acn01_light') }}"
      turn_on:
        service: homeassistant.turn_on
        entity_id: light.lumi_lumi_relay_c2acn01_light 
      turn_off:
        service: homeassistant.turn_off
        entity_id: light.lumi_lumi_relay_c2acn01_light 
    master_bath_fan:
      friendly_name: "Master Bathroom Fan"
      value_template: "{{ states('light.lumi_lumi_relay_c2acn01_light_4') }}"
      turn_on:
        service: homeassistant.turn_on
        entity_id: light.lumi_lumi_relay_c2acn01_light_4 
      turn_off:
        service: homeassistant.turn_off
        entity_id: light.lumi_lumi_relay_c2acn01_light_4 
