- platform: onkyo
  host: !secret avr_ip 
  sources:
    hdmi-6: 'hdmi-6'
    hdmi-5: 'hdmi-5'
    strm-box: 'Home Assistant'
    bd: 'XBOX'
    bluetooth: 'Bluetooth'
    # usb_usb: 'USB'
    network_net: 'Network'
    fm: 'Radio'
    am: 'AM'
    video4: 'Video 4'
    video3: 'Game'
    video2: 'Amos'
    #'cd_tv/cd': 'CD'
    tv: 'TV'
    phono: 'Phono'
    aux: 'AUX'
  name: receiver
  receiver_max_volume: 200 
- platform: gstreamer
  #pipeline: 'audioconvert ! audioresample ! autoaudiosink' 
  pipeline: 'audioconvert ! alsasink latency-time=4'
- platform: samsungtv_encrypted
  host: !secret livingroomtv_ip
  token: !secret livingroomtv_token
  sessionid: !secret livingroomtv_duid
  port: 8080
  name: Living Room TV

