# Describes the format for available Husqvarna Automower services

calendar:
  name: Calendar
  description: This service deletes all of your calendar tasks and replaces it with a new one.
  target:
    entity:
      integration: "husqvarna_automower"
      domain: "vacuum"
  fields:
    start:
      name: Starting time
      description: When the mower should start mowing (must be earlier than the ending time, seconds will be ignored)
      required: true
      example: "11:11:00"
      default: "12:00:00"
      selector:
        time:
    end:
      name: Ending time
      description: When the mower should return to the dock (must be later than the starting time, seconds will be ignored)
      required: true
      example: "17:30:00"
      default: "18:00:00"
      selector:
        time:
    monday:
      name: Monday
      description: Do you wish, that your lawn is mowed on this day?
      required: true
      example: true
      default: true
      selector:
        boolean:
    tuesday:
      name: Tuesday
      description: Do you wish, that your lawn is mowed on this day?
      required: true
      example: true
      default: true
      selector:
        boolean:
    wednesday:
      name: Wednesday
      description: Do you wish, that your lawn is mowed on this day?
      required: true
      example: true
      default: true
      selector:
        boolean:
    thursday:
      name: Thursday
      description: Do you wish, that your lawn is mowed on this day?
      required: true
      example: true
      default: true
      selector:
        boolean:
    friday:
      name: Friday
      description: Do you wish, that your lawn is mowed on this day?
      required: true
      example: true
      default: true
      selector:
        boolean:
    saturday:
      name: Saturday
      description: Do you wish, that your lawn is mowed on this day?
      required: true
      example: true
      default: true
      selector:
        boolean:
    sunday:
      name: Sunday
      description: Do you wish, that your lawn is mowed on this day?
      required: true
      example: true
      default: true
      selector:
        boolean:

schedule_selector:
  name: Schedule Selector
  description: This service deletes all of your calendar tasks and replaces it with a new one.
  target:
    entity:
      integration: "husqvarna_automower"
      domain: "vacuum"
  fields:
    schedule_selector:
      name: Schedule selector
      description: With this you can select the schedule helper which schould be applied to to mower.
      required: true
      example: schedule.target_schedule
      selector:
        entity:
          domain: schedule

custom_command:
  name: Custom command
  description: "Send a highly individual command to the mower, like a multiple calendar task or a
    command for a new feature, which is not implemented yet by this integration. You can get examples
    from https://developer.husqvarnagroup.cloud/apis/Automower+Connect+API#openapi"
  target:
    entity:
      integration: "husqvarna_automower"
      domain: "vacuum"
  fields:
    command_type:
      name: Command Type
      description: Command type
      required: true
      example: "calendar"
      default: "actions"
      selector:
        select:
          options:
            - "actions"
            - "calendar"
            - "settings"
    json_string:
      name: JSON
      description: "Custom command as JSON"
      required: true
      example: >-
        '{
          "data":{
              "type":"calendar",
              "attributes":{
                "tasks":[
                    {
                      "start":300,
                      "duration":360,
                      "monday":false,
                      "tuesday":true,
                      "wednesday":false,
                      "thursday":false,
                      "friday":false,
                      "saturday":false,
                      "sunday":false
                    },
                    {
                      "start":500,
                      "duration":60,
                      "monday":true,
                      "tuesday":false,
                      "wednesday":false,
                      "thursday":false,
                      "friday":false,
                      "saturday":false,
                      "sunday":false
                    }
                ]
              }
          }
        }'
