action:
- data:
    entity_id:
    - switch.ledvance_plug_00054922_1
  service: switch.turn_off
alias: Turn off the Coffee Pot off if Jeanette is home alone
condition:
  condition: and
  conditions:
  - condition: state
    entity_id: person.ryan
    state: not_home
  - condition: state
    entity_id: person.jeanette
    state: home
trigger:
- at: '14:00:00'
  platform: time
