action:
- data:
    entity_id:
    - switch.ledvance_plug_00054922_1
  service: switch.turn_on
alias: Turn on the Coffee Pot when home (Jeanette)
condition:
  condition: and
  conditions:
  - condition: state
    entity_id: person.ryan
    state: not_home
  - after: 07:00:00
    before: '14:00:00'
    condition: time
trigger:
- entity_id: person.jeanette
  platform: state
  to: home
