action:
- data:
    entity_id:
    - switch.ledvance_plug_00054922_1
  service: switch.turn_on
alias: Turn on Coffee Pot in the morning (Ryan)
condition:
- condition: state
  entity_id: person.ryan
  state: home
trigger:
- at: 06:15:00
  platform: time
