action:
- data:
    message: Water leak deteted at the dishwasher!
    title: Dishwasher Leak
  service: notify.all_ios_devices
- data:
    message: Water leak deteted at the dishwasher!
    title: Dishwasher Leak
  service: notify.pushbullet
alias: Dishwasher Leak Detected
trigger:
- entity_id: binary_sensor.lumi_lumi_sensor_wleak_aq1_027b09f4_1_1280
  platform: state
  to: 'on'
