action:
- data:
    data:
      attachment:
        content-type: jpeg
      entity_id: camera.front_porch_direct
      push:
        category: camera
    message: Front Door Bell Was Rung!
    title: Door Bell Alert
  service: notify.all_ios_devices
- data:
    data:
      image: /api/camera_proxy/camera.front_porch_direct
    message: Front Door Bell Was Rung!
    title: Door Bell Alert
  service: notify.all_android_devices
alias: Front Door Bell Rung
id: 952f4a47953c44fdab090dda91412dbc
trigger:
- entity_id: switch.front_door_bell_rung 
  platform: state
  to: 'on'
