action:
- data:
    data:
      attachment:
        content-type: jpeg
      entity_id: camera.front_porch_direct
      push:
        category: camera
    message: Front Door Bell Was Rung!
    title: Door Bell Alert
  service: notify.all_ios_devices
- data:
    data:
      image: /api/camera_proxy/camera.front_porch_direct
    message: Front Door Bell Was Rung!
    title: Door Bell Alert
  service: notify.all_android_devices
alias: Front Door Bell Rung
trigger:
- entity_id: switch.zha_40c04e54_1_6
  platform: state
  to: 'on'
