action:
- data:
    entity_id: switch.sengled_e1c_nb6_6d0b0400_on_off
  service: homeassistant.turn_off
alias: Christmas Outdoor Lights Off
condition: []
description: ''
trigger:
- at: '22:00:00'
  platform: time
