action:
- data:
    entity_id:
    - light.jasco_products_45856_61d32600_1
    - light.the_home_depot_ecosmart_zbt_a19_cct_bulb_e1dcc4fe_level_light_color_on_off
  service: light.turn_on
alias: Turn on the outside lights if arriving after dusk
condition:
- below: -4.0
  condition: numeric_state
  entity_id: sun.sun
  value_template: '{{ state.attributes.elevation }}'
trigger:
- entity_id: group.home_owners
  platform: state
  to: home
