alias: Power Problem Notification
trigger:
  entity_id: binary_sensor.rpi_power_status 
  platform: state
  to: 'on'
  for:
    minutes: 5
condition:
action:
- service: persistent_notification.create
  data_template:
    message: "RPI Power issue reported."
    title: Power Supply Issue
- service: notify.notify
  data_template:
    message: "RPI Power issue reported."
    title: Power Supply Issue
