action:
- data_template:
    message: RPI Power issue reported.
    title: Power Supply Issue
  service: persistent_notification.create
- data_template:
    message: RPI Power issue reported.
    title: Power Supply Issue
  service: notify.notify
alias: Power Problem Notification
condition: null
id: 49ee629a642b43a7ba796ca000f23f70
trigger:
  entity_id: binary_sensor.rpi_power_status
  for:
    minutes: 5
  platform: state
  to: 'on'
