action:
- entity_id: light.stairway_lights
  service: light.turn_on
alias: Remote Press - Stair Lights On
condition: []
description: ''
trigger:
- event_data:
    command: 'on'
    device_ieee: 14:b4:57:ff:fe:81:56:33
  event_type: zha_event
  platform: event
