action:
  data:
    message: Woodpecker Activity Detected!
    title: Woodpecker Detected!
  service: notify.pushbullet
alias: Alert on Woodpecker Pecking
trigger:
- entity_id: binary_sensor.lumi_lumi_vibration_aq1_02af6e3c_1
  platform: state
  to: 'on'
- entity_id: binary_sensor.zha_02b7eb7f_1_1280
  platform: state
  to: 'on'
- entity_id: binary_sensor.zha_02b7eb7f_1
  platform: state
  to: 'on'
