action:
- data:
    entity_id:
    - switch.xbee_xbee_io_4192cf47_210_6 
  service: switch.turn_off
alias: Turn off bluberry irrigation zone after 20 min 
trigger:
  for:
    minutes: 20 
  platform: state
  entity_id: switch.xbee_xbee_io_4192cf47_210_6 
  to: 'on'
