action:
- data:
    entity_id:
      - switch.irrigation_system_switch_18 
  service: switch.turn_off
alias: Turn off bluberry irrigation zone after 20 min
id: 708a84ea371c4455b34157cee41bc087
trigger:
  entity_id: switch.irrigation_system_switch_18 
  for:
    minutes: 20
  platform: state
  from: 'off'
