action:
- data:
    entity_id:
    - switch.xbee_xbee_io_4192cf47_210_6
  service: switch.turn_off
alias: Turn off bluberry irrigation zone after 20 min
id: 708a84ea371c4455b34157cee41bc087
trigger:
  entity_id: switch.xbee_xbee_io_4192cf47_210_6
  for:
    minutes: 20
  platform: state
  to: 'on'
