action:                                                                                                    
- data:                                                                                                    
    entity_id:                                                                                             
    - switch.xbee_xbee_io_4192cf47_211_6                                                                   
  service: switch.turn_on
alias: Turn on garden irrigation in morning
trigger:
- at: 07:45:00
  platform: time
condition:
  - condition: template
    value_template: >
      {% set last_run = state_attr('automation.turn_on_garden_irrigation_in_morning', 'last_triggered') %}
      {{ last_run is none or (now().date() - last_run.date()).days >= 2 }} 
