action:
- data:
    entity_id:
    - light.bedroom_lights
  service: homeassistant.turn_off
alias: Turn off bedroom lights at night
condition:
- condition: state
  entity_id: person.ryan
  state: home
trigger:
- at: sensor.bedroom_lights_off_time
  platform: time
