action:
  data:
    entity_id: light.master_closet_light_zha_group 
  service: light.turn_on
alias: Mstr Bedroom Closet Lights - On When Opened
id: 16731e371f46408e82c6c6828426cb54
trigger:
- entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_opening 
  platform: state
  to: 'on'
