action:
  data:
    entity_id: light.master_bedroom_closet_zha_group_0x0002
  service: light.turn_off
alias: Mstr Bedroom Closet Lights - Off When Closed
id: 93b51ff9829048218579e6ef904844ed
trigger:
- entity_id: binary_sensor.zha_02c39915_1_6
  platform: state
  to: 'off'
