action:
- data:
    entity_id: light.feibit_inc_co_fzb56_zcw27lx1_0_light 
  service: light.turn_off
alias: Turn off counter light if A/V is off
id: 635ef5930bfc492caef02562737e4b63
trigger:
- entity_id: media_player.receiver
  for: 00:05:00
  platform: state
  to: 'off'
