action:
- data:
    entity_id:
    - light.sunricher_zg9101sac_hp_106770a5_1
  service: light.turn_off
alias: Master Bathroom Not Occupied
condition: []
description: ''
id: 83e074c0f17f4947b8009f44ad76cc14
trigger:
- device_id: 3c59aad704c6450ea1f2090902fbe970
  domain: binary_sensor
  entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_4cd42104_occupancy
  platform: device
  type: not_occupied
