action:
- data:
    entity_id:
    - light.master_bath_vanity_light_light 
  service: light.turn_on
alias: Master Bathroom Occupied
condition: []
description: ''
id: 42b61b10650a4ec6931a97e8db45429d
trigger:
- device_id: 3c59aad704c6450ea1f2090902fbe970
  domain: binary_sensor
  entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_occupancy_3 
  platform: device
  type: occupied
