action:
- data:
    entity_id:
    - light.sunricher_zg9101sac_hp_106770a5_1
  service: light.turn_on
alias: Master Bathroom Occupied
condition: []
description: ''
trigger:
- device_id: 3c59aad704c6450ea1f2090902fbe970
  domain: binary_sensor
  entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_4cd42104_occupancy
  platform: device
  type: occupied
