action:
  entity_id: light.king_of_fans_inc_hbuniversalcfremote_b9572700_level_on_off
  service_template: "{% if is_state('light.bedroom_lights', 'on') %} \n  light.turn_on\n\
    {% else %}\n  light.turn_off\n{% endif %}\n"
alias: Switch Master bedroom fan light with bedside lights
condition:
  condition: or
  conditions:
  - after: 07:00:00
    before: '21:00:00'
    condition: time
  - condition: state
    entity_id: light.king_of_fans_inc_hbuniversalcfremote_b9572700_level_on_off
    state: 'on'
id: ac3f4578aad54563ad420de8ad96c643
trigger:
- entity_id: light.bedroom_lights
  platform: state
  to: 'on'
- entity_id: light.bedroom_lights
  platform: state
  to: 'off'
