action:
- data:
    entity_id:
    - light.office_engineer_lamp_light_2 
  service: light.turn_off
- data:
    entity_id:
    - light.office_ceiling_fan_light_2 
  service: light.turn_off
- data:
    entity_id:
    - fan.office_ceiling_fan_fan_2 
  service: fan.turn_off
alias: Office Not Occupied
condition: 
  condition: state
  entity_id:
    - binary_sensor.cx02up3yv_active
  state: "off"
description: 'Turn office off if unocupied'
id: 0cdd5e8a9d6a44318a1f6ba5a420a204
trigger:
- device_id: b7ddc3dbfa994a4b9b59f9336197bcf1
  domain: binary_sensor
  entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_occupancy 
  platform: device
  type: not_occupied
