action:
- data:
    entity_id:
    - light.osram_lightify_a19_rgbw_00a434be_3
  service: light.turn_off
- data:
    entity_id:
    - light.king_of_fans_inc_hbuniversalcfremote_de4d2900_level_on_off
  service: light.turn_off
- data:
    entity_id:
    - fan.king_of_fans_inc_hbuniversalcfremote_de4d2900_fan
  service: fan.turn_off
alias: Office Not Occupied
condition: []
description: ''
id: 0cdd5e8a9d6a44318a1f6ba5a420a204
trigger:
- device_id: b7ddc3dbfa994a4b9b59f9336197bcf1
  domain: binary_sensor
  entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_b7ec4c04_occupancy
  platform: device
  type: not_occupied
