action:
- data:
    entity_id:
    - light.office_engineer_lamp_light_2 
  service: light.turn_on
- data:
    entity_id:
    - light.office_ceiling_fan_light_2 
  service: light.turn_on
- data:
    entity_id: fan.office_ceiling_fan_fan_2 
    percentage: 33 
  service: fan.set_percentage
alias: Office Occupied Summer
condition: '{{ not is_state(''sensor.downstairs_thermostat_operation_mode'', ''heat'')
  }}'
description: ''
id: ad908542af5d4dfea1c7231486ab777d
trigger:
- device_id: b7ddc3dbfa994a4b9b59f9336197bcf1
  domain: binary_sensor
  entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_occupancy 
  platform: device
  type: occupied
