action:
- data:
    entity_id:
    - light.office_engineer_lamp_light_2 
  service: light.turn_on
- data:
    entity_id:
    - light.office_ceiling_fan_light_2 
  service: light.turn_on
alias: Office Occupied Winter
condition: '{{ is_state(''sensor.downstairs_thermostat_operation_mode'', ''heat'')
  }}'
description: ''
id: 66dc2e18e55443b5a49288bc617569f2
trigger:
- device_id: b7ddc3dbfa994a4b9b59f9336197bcf1
  domain: binary_sensor
  entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_occupancy 
  platform: device
  type: occupied
