action:
- data:
    entity_id:
    - light.osram_lightify_a19_rgbw_00a434be_3
  service: light.turn_on
- data:
    entity_id:
    - light.king_of_fans_inc_hbuniversalcfremote_de4d2900_level_on_off
  service: light.turn_on
alias: Office Occupied Winter
condition: "{{ is_state('sensor.downstairs_thermostat_operation_mode', 'heat') }}" 
description: ''
trigger:
- device_id: b7ddc3dbfa994a4b9b59f9336197bcf1
  domain: binary_sensor
  entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_b7ec4c04_occupancy
  platform: device
  type: occupied
