action:
- device_id: c5c667fcf38349bc804000480f5fab16
  domain: switch
  entity_id: switch.sengled_e1c_nb6_f32d0400_on_off
  type: turn_off
alias: Christmas Tree Off
condition: []
description: ''
trigger:
- at: '22:00:00'
  platform: time
