action:
- device_id: c5c667fcf38349bc804000480f5fab16
  domain: switch
  entity_id: switch.sengled_e1c_nb6_f32d0400_on_off
  type: turn_off
alias: Christmas Tree Off
condition: []
description: ''
id: 438e3166dd1443329e3477b42251d001
trigger:
- at: input_datetime.system_sleep_time
  platform: time
