action:
- data:
    entity_id: switch.sengled_e1c_nb6_6d0b0400_on_off
  service: homeassistant.turn_off
alias: Christmas Outdoor Lights Off
condition: []
description: ''
id: 80e3dd63555f4c5ebba28545933fe0dd
trigger:
- at: input_datetime.system_sleep_time
  platform: time
