action:
- data:
    entity_id:
    - light.garage_walk_in_door_light_light 
    - light.deck_light_light_2 
  service: homeassistant.turn_on
alias: Back Porch Light on if Back Door Opened
condition:
- below: '-4'
  condition: numeric_state
  entity_id: sun.sun
  value_template: '{{ state.attributes.elevation }}'
description: ''
id: 9906146158d54663997a7ffa2c5422e1
trigger:
- entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_opening_2 
  platform: state
  to: 'on'
- entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_opening_5 
  platform: state
  to: 'on'
