action:
- data:
    entity_id:
    - light.the_home_depot_ecosmart_zbt_a19_cct_bulb_e1dcc4fe_level_light_color_on_off
    - light.the_home_depot_ecosmart_zbt_a19_cct_bulb_af8ed7fe_level_light_color_on_off
  service: homeassistant.turn_on
alias: Garage walk-in Light on if Door Opened
condition:
- below: '-4'
  condition: numeric_state
  entity_id: sun.sun
  value_template: '{{ state.attributes.elevation }}'
description: ''
trigger:
- entity_id: binary_sensor.zha_02bfe504_1_6
  platform: state
  to: 'on'
