action:
- data:
    entity_id:
    - light.outdoor_lights
  service: homeassistant.turn_off
alias: Porch Lights Off
condition: []
description: At system sleep time or more than 1.5 deg above the horizon
trigger:
- at: input_datetime.system_sleep_time 
  platform: time
- above: '1.5'
  entity_id: sun.sun
  platform: numeric_state
  value_template: '{{ state.attributes.elevation }}'
