action:
- data:
    entity_id:
    - light.outdoor_lights_zha_group 
  service: light.turn_on
alias: Turn on the outside lights if arriving after dusk
condition:
- below: -4.0
  condition: numeric_state
  entity_id: sun.sun
  value_template: '{{ state.attributes.elevation }}'
id: c52287b157974c959bf471ca38c22871
trigger:
- entity_id: group.home_owners
  platform: state
  to: home
