action:
- data:
    entity_id:
    - light.outdoor_lights
  service: homeassistant.turn_on
alias: Porch Lights on at Dusk/Dawn
condition: []
description: 'Turn Porch Lights on at Dusk or Dawn'
trigger:
- below: '-4.0'
  entity_id: sun.sun
  platform: numeric_state
  attribute: elevation
- platform: time
  at: sensor.outdoor_lights_on
