action:
- data:
    entity_id:
    - light.outdoor_lights
  service: homeassistant.turn_on
alias: Porch Lights on at Dusk/Dawn
condition: []
description: Turn Porch Lights on at Dusk or Dawn
id: d446d15724aa41f68fb31817610056f5
trigger:
- attribute: elevation
  below: '-4.0'
  entity_id: sun.sun
  platform: numeric_state
- at: sensor.outdoor_lights_on
  platform: time
