action:
- data:
    entity_id:
    - light.jasco_products_45856_61d32600_1
    - light.the_home_depot_ecosmart_zbt_a19_cct_bulb_e1dcc4fe_level_light_color_on_off
    - light.the_home_depot_ecosmart_zbt_a19_cct_bulb_af8ed7fe_level_light_color_on_off
    - switch.sengled_e1c_nb6_6d0b0400_on_off
  service: homeassistant.turn_off
alias: Porch Lights Off
condition: []
description: At 2200 or more than 1.5 deg above the horizon
trigger:
- at: '22:00:00'
  platform: time
- above: '1.5'
  entity_id: sun.sun
  platform: numeric_state
  value_template: '{{ state.attributes.elevation }}'
