action:
- data:
    entity_id: light.front_porch_lights_light 
  service: homeassistant.turn_on
alias: Porch Light on if Front Door Opened
condition:
- below: -4.0
  condition: numeric_state
  entity_id: sun.sun
  value_template: '{{ state.attributes.elevation }}'
description: ''
id: 1f23d1fe1a254f8783f8d9744dfb0563
trigger:
- entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_opening_3 
  platform: state
  to: 'on'
