action:
  data:
    entity_id: light.hvac_booster_fan_light_2 
  service: light.turn_off
alias: Turn Circulation Fan off With HVAC
condition:
- condition: state
  entity_id: sensor.downstairs_thermostat_hvac_state
  state: 'off'
- condition: state
  entity_id: binary_sensor.downstairs_thermostat_fan
  state: 'off'
id: 255ff23b450e4aac9c2eab13dfde213a
trigger:
- entity_id: sensor.downstairs_thermostat_hvac_state
  platform: state
  to: 'off'
- entity_id: binary_sensor.downstairs_thermostat_fan
  platform: state
  to: 'off'
