action:
  data:
    entity_id: light.hvac_booster_fan_light_2 
  service: light.turn_on
alias: Turn Circulation Fan on With HVAC
id: 9c2112dd117a412c86263f3465e76591
trigger:
- entity_id: binary_sensor.downstairs_thermostat_fan
  from: 'off'
  platform: state
