action:
- data:
    entity_id: switch.zha_40c04dcb_1_6
  service: switch.turn_on
alias: Set Water Heater on if restarted and home 
condition:
  condition: and
  conditions:
    - "{{ (strptime(states('sensor.water_heater_start_time'), '%Y-%m-%dT%H:%M:%S%z')) < now() }}"
    - "{{ (strptime(states('sensor.water_heater_off_time'), '%Y-%m-%dT%H:%M:%S%z')) > now() }}"
    - "{{ states('group.home_owners') == 'home'}}"
trigger:
  platform: homeassistant
  event: start
