action:
- data:
    entity_id: switch.zha_40c04dcb_1_6
  service: switch.turn_on
alias: Set Water Heater on When Home
condition:
  condition: and
  conditions:
    - "{{ (strptime(states('sensor.water_heater_start_time'), '%H:%M:%S')) < now() }}"
    - "{{ (strptime(states('sensor.water_heater_off_time'), '%H:%M:%S')) > now() }}"
trigger:
- entity_id: group.home_owners
  platform: state
  to: home
