action:
- data:
    entity_id: switch.zha_40c04dcb_1_6
  service: switch.turn_on
alias: Set Water Heater on in the Morning
condition:
- condition: state
  entity_id: group.home_owners
  state: home
trigger:
- at: sensor.water_heater_start_time 
  platform: time
