action:
- data:
    entity_id: switch.water_heater_switch 
  service: switch.turn_off
alias: Set Water Heater off at night
id: 1ebbb228fdf4477e8104d736bea059a1
trigger:
- at: sensor.water_heater_off_time
  platform: time
