action:
- data:
    entity_id: switch.water_heater_switch 
  service: switch.turn_off
alias: Set Water Heater off When Away
id: aa8b8d393e2244c7bad1d0df6336c5ae
trigger:
- entity_id: group.home_owners
  platform: state
  to: not_home
