action:
- data:
    entity_id: switch.water_heater_switch 
  service: switch.turn_on
alias: Water Heater Emergency Heat
id: 0066a613ad8649d98269ef198945f2b1
trigger:
- below: 45
  entity_id: sensor.water_heater_temperature_2 
  platform: numeric_state
