action:
- data: ''
  service: rest_command.turn_off_amos 
alias: Power Amos off on Power Failure
id: a91fc468b2d34aac9b590554343363d5
trigger:
- below: 60
  entity_id: sensor.serverroom_battery_charge
  platform: numeric_state
