action:
- service: homeassistant.turn_on
  entity_id: group.nonessential_ups
- data:
    data:
      push:
        sound:
          critical: 1
          name: default
          volume: 1.0
    message: Server Power Restored!
    title: Server Power Restored
  service: notify.all_ios_devices
- data:
    data:
      priority: high
      ttl: 0
    message: Server Power Restored!
    title: Server Power Restored
  service: notify.all_android_devices
alias: Server Power Restored
id: 6f61d4807b8943539bed0205fe379bd7
trigger:
- entity_id: sensor.serverroom_status
  from: On Battery Battery Discharging
  platform: state
  to: Online
- entity_id: sensor.serverroom_status
  platform: state
  to: Online Battery Charging
