action:
- data:
    message: It's trash day and the dumpster is still inside the garage.
    title: Take Dumpster Outside
  service: notify.all_android_devices
alias: Set Dumpster Outside
condition:
- after: 02:30:00
  before: 09:30:00
  condition: time
  weekday:
  - fri
- condition: state
  entity_id: sensor.dumpster
  state: garage
id: 0af778663e7541448750d51e4129f9f1
trigger:
- at: 08:00:00
  platform: time
- entity_id: switch.garage_door_switch_4 
  platform: state
  to: 'on'
