action:
- data:
    message: The dumpster is still outside, please bring it back inside.
    title: Bring Dumpster Inside
  service: notify.all_android_devices
alias: Bring Dumpster In
condition:
- after: '10:30:00'
  condition: time
  weekday:
  - fri
- condition: state
  entity_id: sensor.dumpster
  state: not_home
id: ca9bf3a7498a4aefac795b2d35518c06
trigger:
- at: '11:00:00'
  platform: time
- entity_id: switch.garage_door_switch_4 
  platform: state
  to: 'on'
